### ISSUE TITLE
Any release plan?

### ISSUE THREAD

**Issue by mxj4** [khaledhosny/libmathview#22]
Hi Khaled,

Calligra development version depends on libmathview now. If libmathview has an official release, it will make things easier for various linux distro maintainers when new calligra version releases. Is there any plan to have an official release?

Thanks.

**Comment by khaledhosny** [comment]
I really need to cleanup the OpenType math support a bit before making a release, what is the time frame for the Calligra release that depends on libmathview? Or is it already released?

**Comment by behdad** [comment]
Remind me... I know I've been horrible about this:

Do you need HarfBuzz API for table access for this?  Let's take another look at that.

**Comment by behdad** [comment]
I guess, alternatively, it's ok to say you should load the table yourself, if this is a limited-use table.  I'd say HarfBuzz's internal types are useful for something like that, and maybe there's way that we expose them.

**Comment by mxj4** [comment]
no there is no release plan for calligra, still need several months I guess.

**Comment by khaledhosny** [comment]
> Do you need HarfBuzz API for table access for this? Let's take another look at that.

I’m currently (partially) parsing the table on my own, but the code is ugly and I’d prefer if HarfBuzz did it for me, but I’m yet to warp my head around table parsing in HarfBuzz to contribute anything useful here.

**Comment by khaledhosny** [comment]
> no there is no release plan for calligra, still need several months I guess.

OK, no hurry then. Let me try to work again on this and hopefully be able to make a release before Calligra is released.

**Comment by behdad** [comment]
> I’m currently (partially) parsing the table on my own, but the code is ugly and I’d prefer if HarfBuzz did it for me, but I’m yet to warp my head around table parsing in HarfBuzz to contribute anything useful here.

Can you point me to your code?  I remember there was a thread on HarfBuzz list where you listed what kind of API you need, but I cannot find it.

**Comment by khaledhosny** [comment]
The code is here: https://github.com/khaledhosny/libmathview/blob/master/src/backend/MathFont.cc, not very complete though. But roughly API we need is access to math constants, access to glyph properties (italic correction, accent position and math kerning), and access to size variants including assemblies.

**Comment by KrasnayaPloshchad** [comment]
Since HarfBuzz got support, this work would easy to do.

**Comment by khaledhosny** [comment]
@philacs feel free to remind me when Calligra release is close to finish the HarfBuzz switch and cut a release.

**Comment by KrasnayaPloshchad** [comment]
CC @fred-wang

**Comment by fred-wang** [comment]
@KrasnayaPloshchad Any specific reason why you cc' me? May I help with something?

**Comment by KrasnayaPloshchad** [comment]
@fred-wang Hopefully, your contributions would help this library released soon.

**Comment by khaledhosny** [comment]
I’m no longer interested in this library and I’m archiving this repo. If anyone is still really interested in developing it, please fork.
